import {domain} from "../../config/config"
export const index = domain + "/customer_owner"
export const add = domain + "/customer_owner"
export const item = domain + "/customer_owner"
export const edit = domain + "/customer_owner"
export const del = domain + "/customer_owner"
export const update = domain + "/customer_owner"
